import { Link, useNavigate } from "react-router-dom";
import { ArrowRight, Minus, Plus, Trash2, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useCart } from "@/lib/cart";

export default function CartDrawer() {
  const { isOpen, closeCart, items, subtotal, updateQuantity, removeItem } = useCart();
  const navigate = useNavigate();
  if (!isOpen) return null;
  const remaining = Math.max(999 - subtotal, 0);
  const progress = Math.min((subtotal / 999) * 100, 100);
  return <div className="drawer-layer" data-testid="cart-drawer"><button className="drawer-scrim" onClick={closeCart} aria-label="Close cart" data-testid="cart-drawer-scrim" /><aside className="cart-panel" role="dialog" aria-modal="true" aria-labelledby="cart-title"><div className="cart-panel-head"><div><p className="eyebrow">Your selection</p><h2 id="cart-title">Cart <span>({items.reduce((sum, item) => sum + item.quantity, 0)})</span></h2></div><Button variant="ghost" size="icon" onClick={closeCart} aria-label="Close cart" data-testid="cart-drawer-close"><X /></Button></div>
    {items.length === 0 ? <div className="cart-empty"><div className="empty-mark">○</div><h3>Your cart is quiet.</h3><p>Add a fragrance and it will appear here.</p><Link to="/collection" className="gold-link" onClick={closeCart} data-testid="cart-empty-shop-link">Explore collection <ArrowRight size={15} /></Link></div> : <><div className="shipping-progress"><div className="shipping-progress-copy"><span>{remaining > 0 ? `₹${remaining.toLocaleString("en-IN")} away from free shipping` : "You have unlocked free shipping"}</span><span>{Math.round(progress)}%</span></div><div className="progress-track"><div style={{ width: `${progress}%` }} /></div></div><div className="cart-items">{items.map((item) => <div className="cart-item" key={`${item.product.id}-${item.sizeMl}`} data-testid={`cart-item-${item.product.slug}`}><img src={item.product.image_url} alt="" /><div className="cart-item-copy"><div className="cart-item-title"><div><p>{item.product.name}</p><small>{item.sizeMl} ml</small></div><button type="button" onClick={() => removeItem(item.product.id, item.sizeMl)} aria-label={`Remove ${item.product.name}`} data-testid={`cart-item-remove-${item.product.slug}`}><Trash2 size={14} /></button></div><div className="cart-item-bottom"><div className="quantity-stepper"><button type="button" onClick={() => updateQuantity(item.product.id, item.sizeMl, item.quantity - 1)} disabled={item.quantity === 1} aria-label="Decrease quantity" data-testid={`cart-item-decrement-${item.product.slug}`}><Minus size={13} /></button><span data-testid={`cart-item-quantity-${item.product.slug}`}>{item.quantity}</span><button type="button" onClick={() => updateQuantity(item.product.id, item.sizeMl, item.quantity + 1)} aria-label="Increase quantity" data-testid={`cart-item-increment-${item.product.slug}`}><Plus size={13} /></button></div><strong>₹{(item.unitPrice * item.quantity).toLocaleString("en-IN")}</strong></div></div></div>)}</div><div className="cart-panel-foot"><div className="cart-subtotal"><span>Subtotal</span><strong>₹{subtotal.toLocaleString("en-IN")}</strong></div><Button className="full-button" onClick={() => { closeCart(); navigate("/checkout"); }} data-testid="cart-checkout-button">Checkout <ArrowRight /></Button><p className="secure-copy">No account needed · Secure checkout · India-wide delivery</p></div></>}
  </aside></div>;
}
