import { Link, useParams } from "react-router-dom";
import { ArrowLeft } from "lucide-react";

const content: Record<string, { title: string; intro: string; sections: Array<[string, string]> }> = {
  privacy: { title: "Privacy policy", intro: "A clear note on the information we collect and why.", sections: [["What we collect", "When you place an order or contact us, we collect the details needed to deliver, reply and support your purchase. We do not sell personal information."], ["How we use it", "Order details are used for fulfilment, customer care and essential updates. Newsletter messages are sent only with consent and can be stopped anytime."], ["Questions", "Write to hello@makemyperfume.in and our studio will help."]] },
  terms: { title: "Terms", intro: "The simple terms behind a thoughtful purchase.", sections: [["Orders", "Orders are confirmed after the details and payment method are accepted. Product availability and pricing may change before confirmation."], ["Your responsibility", "Please provide a reachable phone number and accurate Indian delivery address. We cannot be responsible for delays caused by incorrect details."], ["Support", "For questions about an order, contact us with your order reference."]] },
  "shipping-returns": { title: "Shipping & returns", intro: "What to expect after you press place order.", sections: [["Delivery", "We deliver across India. Shipping is complimentary on orders over ₹999 and ₹99 below that threshold. Typical delivery is 3–7 business days."], ["Returns", "Unopened, unused products can be requested for return within 7 days of delivery. Please keep the packaging intact while we review your request."], ["COD", "Cash on delivery includes a clearly shown ₹80 handling fee before confirmation."]] },
  "refund-policy": { title: "Refund policy", intro: "A transparent approach to refunds and cancellations.", sections: [["When refunds apply", "Approved returns, cancelled prepaid orders and confirmed delivery issues are eligible for a refund to the original payment method."], ["Timeline", "Once approved, refunds are initiated within 5 business days. Your bank or payment provider may take additional time to reflect it."], ["Need help", "Email hello@makemyperfume.in with your order reference and we’ll take care of the rest."]] },
};

export default function Policy() { const { slug = "privacy" } = useParams(); const page = content[slug] ?? content.privacy; return <div className="policy-page page-width" data-testid={`policy-page-${slug}`}><Link to="/" className="back-link" data-testid="policy-back-link"><ArrowLeft size={15} /> Back home</Link><div className="policy-header"><p className="eyebrow">Good to know</p><h1>{page.title}</h1><p>{page.intro}</p></div><div className="policy-sections">{page.sections.map(([title, body]) => <section key={title}><p className="eyebrow">{title}</p><p>{body}</p></section>)}</div></div>; }
